version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: eventra_db
      POSTGRES_USER: eventra_user
      POSTGRES_PASSWORD: eventra_password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
